In [11]:
import numpy as np

In [12]:
nums = [1,2,35,65]

In [13]:
np.array(nums)

array([ 1,  2, 35, 65])

In [18]:
two_d_array = [nums,[3,5,6,6]]

In [19]:
np.array(two_d_array)

array([[ 1,  2, 35, 65],
       [ 3,  5,  6,  6]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.ones(45)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((30,100))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [38]:
np.random.rand(5)

array([0.63329505, 0.13921044, 0.20520109, 0.80875874, 0.70806851])

In [39]:
np.random.rand(3,4)

array([[0.42232238, 0.2745286 , 0.03305654, 0.39198625],
       [0.94482877, 0.35885476, 0.23900061, 0.0404349 ],
       [0.28567892, 0.24024556, 0.65798337, 0.09717009]])

In [36]:
np.random.randn(3,5)

array([[-0.26632822, -0.61418467, -0.72633126, -1.5386968 , -0.09130484],
       [-0.57983669, -0.56706393,  1.5645101 , -0.81309774,  0.1069196 ],
       [ 0.27168881,  2.74969636, -0.05741803,  0.20217229, -0.74006698]])

In [40]:
np.random.randn(4)

array([-0.55432396, -0.82492743,  1.50953929, -1.4810447 ])

In [41]:
np.random.randint(1,10,5)

array([7, 4, 5, 9, 1], dtype=int32)

In [54]:
numbers = np.random.randint(1,50,50)

In [55]:
numbers

array([38, 27, 17,  6, 31,  2, 20, 21,  3, 30, 31, 34, 10, 47,  4, 20,  3,
       27, 31, 46,  3, 17,  2, 47, 45, 28, 14, 11, 39, 41, 20, 31, 12, 38,
       28, 20, 21, 31, 46, 31, 33,  5, 39, 36,  7, 32, 17, 45, 28, 12],
      dtype=int32)

In [56]:
numbers.reshape(2,25)

array([[38, 27, 17,  6, 31,  2, 20, 21,  3, 30, 31, 34, 10, 47,  4, 20,
         3, 27, 31, 46,  3, 17,  2, 47, 45],
       [28, 14, 11, 39, 41, 20, 31, 12, 38, 28, 20, 21, 31, 46, 31, 33,
         5, 39, 36,  7, 32, 17, 45, 28, 12]], dtype=int32)

In [57]:
numbers.max()

np.int32(47)

In [58]:
numbers.min()

np.int32(2)

In [59]:
numbers.argmin()

np.int64(5)

In [60]:
numbers.argmax()

np.int64(13)

In [61]:
numbers.shape

(50,)

## NumPy Indexing and Selection

In [65]:
NUMS = np.array([1,3,4,5])

In [66]:
NUMS

array([1, 3, 4, 5])

In [67]:
NUMS[2]

np.int64(4)

In [68]:
NUMS[1]

np.int64(3)

In [69]:
NUMS[:3]

array([1, 3, 4])

In [70]:
NUMS[2:
]

array([4, 5])

In [72]:
nums = np.arange(1, 100)

In [73]:
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [74]:
np.array(nums)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
nums[:6]

array([1, 2, 3, 4, 5, 6])

In [76]:
nums[:6] = 100

In [77]:
nums

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99])

In [78]:
nums[:6
]

array([100, 100, 100, 100, 100, 100])

In [79]:
x = np.arange(10
             )

In [80]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x[:5]

array([0, 1, 2, 3, 4])

In [82]:
x[:5] = 20

In [83]:
x

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [85]:
y = [3,4,56,2]

In [86]:
y

[3, 4, 56, 2]

In [106]:
sliced_y = y[:3
]

In [107]:
sliced_y = y[:2].copy()

In [108]:
sliced_y

[3, 4]

In [109]:
sliced_y = 100

In [110]:
sliced_y

100

In [111]:
z = np.arange(10)

In [112]:
z= np.array(z)

In [113]:
sliced_z = z[:4]

In [114]:
sliced_z

array([0, 1, 2, 3])

In [115]:
sliced_z = 100

sliced_z

## GRABBING 2D USING []][] OR [,]

In [126]:
n = np.array([[2,6,7],[2,5,6],[6,75,3]])

In [127]:
n

array([[ 2,  6,  7],
       [ 2,  5,  6],
       [ 6, 75,  3]])

In [128]:
n[1][2]

np.int64(6)

In [130]:
n[2,1]

np.int64(75)

In [132]:
n[1:3,:2]

array([[ 2,  5],
       [ 6, 75]])

In [140]:
nums = np.arange(20,37)

In [141]:
nums

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

In [142]:
bool_nums = nums > 40

In [143]:
bool_nums

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [145]:
bool_nums = nums >=28

In [146]:
bool_nums

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [147]:
nums[bool_nums]

array([28, 29, 30, 31, 32, 33, 34, 35, 36])

In [150]:
arr_2d = np.arange(50).reshape(5,10) +1

In [151]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

## NumPy Operations

In [153]:
num = nums[bool_nums]

In [154]:
num

array([28, 29, 30, 31, 32, 33, 34, 35, 36])

In [155]:
num + num

array([56, 58, 60, 62, 64, 66, 68, 70, 72])

In [156]:
num - num

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [157]:
num * num

array([ 784,  841,  900,  961, 1024, 1089, 1156, 1225, 1296])

In [160]:
num ** 3

array([21952, 24389, 27000, 29791, 32768, 35937, 39304, 42875, 46656])

In [161]:
num / num

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [162]:
num / 45

array([0.62222222, 0.64444444, 0.66666667, 0.68888889, 0.71111111,
       0.73333333, 0.75555556, 0.77777778, 0.8       ])

In [164]:
np.add(num[1],num[2])

np.int64(59)